# Generated by Django 3.1 on 2022-06-29 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolStaff',
            fields=[
                ('id_staff', models.AutoField(primary_key=True, serialize=False)),
                ('rol_description', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'RolStaff',
                'verbose_name_plural': 'RolStaffs',
                'db_table': 'rolstaff',
            },
        ),
        migrations.CreateModel(
            name='CoachingStaff',
            fields=[
                ('id_staff', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('last_name', models.CharField(max_length=250, unique=True)),
                ('date_born', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.rolstaff')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'verbose_name': 'CoachingStaff',
                'verbose_name_plural': 'CoachingStaffs',
                'db_table': 'coachingstaff',
                'unique_together': {('name', 'last_name')},
            },
        ),
    ]
