# Generated by Django 3.1 on 2022-06-29 15:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20220629_0050'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coachingstaff',
            managers=[
                ('coachs', django.db.models.manager.Manager()),
            ],
        ),
    ]
