# Generated by Django 3.1 on 2022-06-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20220629_1001'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coachingstaff',
            managers=[
            ],
        ),
    ]
