# Generated by Django 3.1 on 2022-06-29 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del jugador')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido del jugador')),
                ('date_born', models.DateField(verbose_name='Fecha de nacimiento del jugador')),
                ('position', models.CharField(choices=[('POR', 'Portero'), ('CAD', 'Carrilero Derecho'), ('LTD', 'Lateral Derecho'), ('DFC', 'Defensa Central'), ('LTI', 'Lateral Izquierdo'), ('CAI', 'Carrilero Izquierdo'), ('MCD', 'Medio Centro Defensivo'), ('MD', 'Medio Derecho'), ('MC', 'Medio Centro'), ('MI', 'Medio Izquierdo'), ('MCO', 'Medio Centro Ofensivo'), ('SDD', 'Segundo Delantero Derecho'), ('MP', 'Media Punta'), ('SDI', 'Segundo Delantero Izquierdo'), ('ED', 'Extremo Derecho'), ('DC', 'Delantero Centro'), ('EI', 'Extremo Izquierdo')], max_length=4, verbose_name='Posicion en el campo de juego')),
                ('number_jersey', models.IntegerField(verbose_name='Numero del dorsal del jugador')),
                ('titular', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Seleccion')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'player',
            },
        ),
    ]
