# Generated by Django 3.1 on 2022-06-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_img',
            field=models.ImageField(upload_to='players'),
        ),
    ]
