# Generated by Django 3.1 on 2022-06-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20220628_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_img',
            field=models.ImageField(upload_to='img/players'),
        ),
    ]
