
PLAYER_POSITIONS = (
    ('POR',	'Portero'),
    ('CAD',		'Carrilero Derecho'),
    ('LTD',	'Lateral Derecho'),
    ('DFC',	'Defensa Central'),
    ('LTI',	'Lateral Izquierdo'),
    ('CAI',		'Carrilero Izquierdo'),
    ('MCD',		'Medio Centro Defensivo'),
    ('MD',	'Medio Derecho'),
    ('MC',	'Medio Centro'),
    ('MI',	'Medio Izquierdo'),
    ('MCO',		'Medio Centro Ofensivo'),
    ('SDD',	'Segundo Delantero Derecho'),
    ('MP',	'Media Punta'),
    ('SDI',	'Segundo Delantero Izquierdo'),
    ('ED',	'Extremo Derecho'),
    ('DC',	'Delantero Centro'),
    ('EI',	'Extremo Izquierdo'),
)
