# Generated by Django 3.1 on 2022-06-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='url_flag',
            field=models.ImageField(upload_to='flags'),
        ),
        migrations.AlterField(
            model_name='team',
            name='url_shield',
            field=models.ImageField(upload_to='shields'),
        ),
    ]
