# Generated by Django 3.1 on 2022-06-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20220628_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='url_flag',
            field=models.ImageField(blank=True, null=True, upload_to='img/flags'),
        ),
        migrations.AlterField(
            model_name='team',
            name='url_shield',
            field=models.ImageField(blank=True, null=True, upload_to='img/shields'),
        ),
    ]
