# Generated by Django 3.1 on 2022-06-29 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20220628_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('name',), 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
