# Generated by Django 3.1 on 2022-06-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20220628_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='url_flag',
            new_name='img_flag',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='url_shield',
            new_name='img_shield',
        ),
    ]
