# Generated by Django 3.1 on 2022-06-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20220628_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='img_shield',
        ),
        migrations.AlterField(
            model_name='team',
            name='img_flag',
            field=models.ImageField(blank=True, null=True, upload_to='img/shields'),
        ),
    ]
