# Generated by Django 3.1 on 2022-06-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20220629_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img_shield',
            field=models.ImageField(blank=True, null=True, upload_to='img/shields'),
        ),
    ]
